### PR TITLE
Remove vendor-specific CSS

### PR DESCRIPTION
**Pull request by AllThingsSmitty**
Certain -moz- and -o- prefixes are no longer needed.

### CODE REVIEW

**Comment by QWp6t** [comment]
I think in the src all vendor prefixes should be removed and the build process should use autoprefixer to add prefixes as needed for dist.

**Comment by alrra** [comment]
Related to #1671.

**Comment by battaglr** [comment]
@AllThingsSmitty: what's your definition of "no longer needed"? AFAIK, Gecko only supports the prefixed version of `::selection`. You can check [this](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#compat_hint1), and [this](https://bugzilla.mozilla.org/show_bug.cgi?id=509958).

And I'm not sure about the media queries for print, but apparently Webkit [doesn't support](https://developer.mozilla.org/en/docs/Web/CSS/resolution#Browser_compatibility) `min-resolution`.

:-1: to this PR.

**Although**, I agree with @QWp6t's idea to add Autoprefixer for dist.

**Comment by AllThingsSmitty** [comment]
@battaglr that's odd because Autoprefixer is what flagged those items for me, including `::selection`.

**Comment by battaglr** [comment]
@AllThingsSmitty: that's indeed really odd. Although I trust in the MDN documentation, we could check other sources.

**Comment by AllThingsSmitty** [comment]
@battaglr I'll open an issue with Autoprefixer and see if they can validate [Mozilla's `::selection`](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#compat_hint1) requirement, too.

**Comment by battaglr** [comment]
Awesome! Can you please reference the issue so we can keep track of it?

**Comment by AllThingsSmitty** [comment]
Issue [#417](https://github.com/postcss/autoprefixer/issues/417) opened with Autoprefixer project to further research this rule

**Comment by AllThingsSmitty** [comment]
Closing this issue as I look into that matter with Autoprefixer further. Reference [Autoprefixer issue #417](https://github.com/postcss/autoprefixer/issues/417).

**Pull request closed without merging**
