### PR TITLE
Update README.md to point to browserslist in package.json

### PR DESCRIPTION
**Pull request by isaac-friedman**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

None of the above. I updated the README to accuratel reflect the browsers we support based on `package.json`.
## Checklist:

- [x] My code follows the code style of this project. (N/A)
- [x] My change requires a change to the documentation. (It is a documentation change)
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Comment by roblarsen** [comment]
Thanks, I had missed the text of #2623. I don't like this approach without the addition of actual human-readable words. Pointing people to browserlist syntax and telling them to parse that to figure out what we support isn't user-friendly. So, this is a good start, but I'm going to add some text to explain what it means in simple language.

**Comment by isaac-friedman** [comment]
> 
> 
> Thanks, I had missed the text of #2623. I don't like this approach without the addition of actual human-readable words. Pointing people to browserlist syntax and telling them to parse that to figure out what we support isn't user-friendly. So, this is a good start, but I'm going to add some text to explain what it means in simple language.

I agree. I'll add some humn-readable text but I still want to keep the browserlist syntax in addition.

**Comment by roblarsen** [comment]
Sounds good!

**Comment by roblarsen** [comment]
I'll merge this and then add some docs

**Pull request merged**
