### PR TITLE
Partially revert vendor prefixes

### PR DESCRIPTION
**Pull request by corvannoorloos**
It appears the Autoprefixer task has been run in between updating its settings during this request #1682.

### CODE REVIEW

**Comment by alrra** [comment]
@corvannoorloos Their removal was intentional (see [`dist/main.css`](https://github.com/h5bp/html5-boilerplate/blob/9581cf3a81ea396e73360ac3a99b8d453f9358e7/dist/css/main.css)). Also, wasn't that the whole point of adding Autoprefixer? :)

**Comment by corvannoorloos** [comment]
@alrra true, which is why the __partial__ revert. If I'm not misinterpreting something here some of the sections were removed when ie8 wasn't yet included.

See the differences between dist and src.

**Comment by alrra** [comment]
> which is why the partial revert. If I'm not misinterpreting something here some of the sections were removed when ie8 wasn't yet included.
> 
> See the differences between dist and src.

@corvannoorloos I do apologize, but I don't really understand why would you want to add them back.  The whole point of using Autoprefixer was to eliminate the need to add those vendor prefixes manually, and instead, let Autoprefixer do that for us at build time. Which is what happens now, we don't have the vendor prefixes in `src/css/main.css`, but when we generate the `dist/css/main.css` directory, they get added automatically based on what browsers we support.

>  some of the sections were removed when ie8 wasn't yet included.

@corvannoorloos Before I merged that pull request I did all the necessary changes to ensure that everything was as intended.

**Comment by corvannoorloos** [comment]
@alrra you're completely right. No idea where my mind was when making this request :)

I apologize and thanks again.

**Comment by alrra** [comment]
> No idea where my mind was when making this request :)
>  I apologize and thanks again.

@corvannoorloos No problem at all, enjoy the weekend!

**Pull request closed without merging**
