### PR TITLE
Add 'end_of_line = lf' to .editorconfig

### PR DESCRIPTION
**Pull request by BennyBPB**
Added line feed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Comment by coliff** [comment]
Great PR! Strange we've missed adding that after all these years...

**Comment by coliff** [comment]
This change should be made in the `src` directory, then when the project is built it'll get copied to `dist`.

**Comment by BennyBPB** [comment]
> This change should be made in the `src` directory, then when the project is built it'll get copied to `dist`.

Added it to the 'src' directory. Should I additionally remove from 'dist'?

**Comment by roblarsen** [comment]
@BennyBPB you can leave it in `./dist`

**Review by roblarsen — APPROVED** [review]

**Review by coliff — APPROVED** [review]

**Pull request merged**
