### PR TITLE
Change jQuery CDN to a China-safe option

### PR DESCRIPTION
**Pull request by roblarsen**
Fixes: #1737

China, with with more web users than there are people in the US, blocks googleaplis.com. We really ought to put the "WORLD" back in World Wide Web with a China-friendly option for jQuery.

### CODE REVIEW

**Comment by hatzopoulos** [comment]
FWIW I once tested a few of them and jQuery's (maxcdn) was faster at the time. Although my testing method was rather crude and done 3 years ago. http://stackoverflow.com/a/12981092/881551

**Comment by chrislaughlin** [comment]
:+1:  looks good and I assume that the official jQuery source would be the best.

**Comment by roblarsen** [comment]
I forgot about this whole discussion. @alrra? (or whoever else has the keys these days...)

**Comment by alrra** [comment]
@roblarsen Can you also update:

  * the docs (see: [`html.md`](https://github.com/h5bp/html5-boilerplate/blob/fc05bc82abf26f4042c86a17652dd232362f78ad/src/doc/html.md#google-cdn-for-jquery) & [`faq.md`](https://github.com/h5bp/html5-boilerplate/blob/fc05bc82abf26f4042c86a17652dd232362f78ad/src/doc/faq.md#why-dont-you-automatically-load-the-latest-version-of-jquery-from-the-google-cdn)) 
  * the commit message to include a little bit more information about why this change is made and that it doesn't have any downsides compared to the current solution (see also the previous discussion: https://github.com/h5bp/html5-boilerplate/issues/1191).

Thanks!

**Comment by roblarsen** [comment]
:+1:  Updated

**Comment by alrra** [comment]
@roblarsen Thanks! :purple_heart: 

--

Merged with some modifications (e.g.: also updated the [`CHANGELOG.md`](https://github.com/h5bp/html5-boilerplate/blob/438b8a7eef5da651ec22170a3540351e004ce90a/CHANGELOG.md)) in 340b012a1f5d096658ecfc3072ca0009ab0f80f3.

**Comment by roblarsen** [comment]
:+1:

**Pull request closed without merging**
