### PR TITLE
ci: push to another repo

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

#2391

Github action to push `dist` folder to another repo (template repo).
Github action used: https://github.com/marketplace/actions/push-directory-to-another-repository

Successfully working:
https://github.com/vltansky/html5-boilerplate pushing to https://github.com/vltansky/html5-boilerplate-template

Probably needed:
- Probably change the trigger from push to release.
- Change:  `destination-github-username`, `destination-repository-name`, `user-email`
- Add `API_TOKEN_GITHUB` to the repository secrets

### CODE REVIEW

**Comment by roblarsen** [comment]
FYI, there are multiple issues in the create repo, so I can't focus on doing this work until that's actually released. It would be safer if you held off on doing more work here without my input. I already want to charge the commit message in the template repo itself

**Comment by roblarsen** [comment]
Pulling these changes into another branch to keep Vlad's commits and I'm going to create a fresh PR for this work

**Comment by vltansky** [comment]
I'm available if you need any help with it

**Comment by roblarsen** [comment]
Thanks @vltansky I think you already did most of the work, but thanks!

**Pull request closed without merging**
