### PR TITLE
Removing humans.txt reference

### PR DESCRIPTION
**Pull request by roblarsen**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
looks good - need to remove mention from `usage.md` too though

**Comment by roblarsen** [comment]
👍 updated!

**Comment by Gpengfei** [comment]
---- Replied Message ----
| From | Rob ***@***.***> |
| Date | 03/04/2023 00:02 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [h5bp/html5-boilerplate] Removing humans.txt reference (PR #2929) |
Types of changes
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to change)
Checklist:
My code follows the code style of this project.
My change requires a change to the documentation.
I have updated the documentation accordingly.
I have read the CONTRIBUTING document.
I have added tests to cover my changes.
All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

You can view, comment on, or merge this pull request online at:

  https://github.com/h5bp/html5-boilerplate/pull/2929

Commit Summary
f40da93 Removing humans.txt reference
File Changes

(1 file)

Mdocs/extend.md (8)
Patch Links:
https://github.com/h5bp/html5-boilerplate/pull/2929.patch
https://github.com/h5bp/html5-boilerplate/pull/2929.diff

**Review by coliff — APPROVED** [review]

**Comment by frankstallone** [comment]
Uhm, why was humans.txt removed?

**Comment by roblarsen** [comment]
@frankstallone #2553 #2584

**Pull request merged**
