### PR TITLE
Update Modernizr to 3.7.0

### PR DESCRIPTION
**Pull request by coliff**
REF: https://github.com/Modernizr/Modernizr/blob/master/CHANGELOG.md

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly. 

Thanks!

### CODE REVIEW

**Comment by coliff** [comment]
Related note; The `modernizr-config.json` in this project is unchanged since May 2017. I personally don't use Modernizr and am not too familiar with the config - but should we be updating any of the options in there?

**Comment by roblarsen** [comment]
We can look at it. We ship an arbitrary default set of tests. They can and should change form time to time. 

I would like to see [https://github.com/Modernizr/Modernizr/issues/2402#issuecomment-469670559](this issue with Modernizr resolved) and then I would release 7.1.0 with the new Modernizr version. As an added bonus I can publicize that Modernizr has restarted (cc: @rejas) If that issue remains stalled, I'll just release a patch with this version.

**Comment by rejas** [comment]
I dont see https://github.com/Modernizr/Modernizr/issues/2402 being resolved from the modernizr site of things any time soon as discussed in the comments. It's not something that modernizr itself can fix easily nor without breaking other stuff and it doesnt affect the actual build. 
So I'd propose too to release 7.1.0 with the current modernizr.

**Comment by roblarsen** [comment]
@rejas thanks. I've been following a number of Modernizr issues so I know the outlook for getting that fixed is grim, I was mostly giving you a heads up that I'll be basically publicizing the new Modernizr release with 7.1.0, which will help you get the word out.

**Pull request merged**
