### PR TITLE
Remove `browserconfig.xml` and the tile images

### PR DESCRIPTION
**Pull request by alrra**
## General information

The `browserconfig.xml` file and the `tile` images were introduced in: https://github.com/h5bp/html5-boilerplate/pull/1481
## Reasons for their removal:
- Support for the [web application manifest file](https://github.com/h5bp/html5-boilerplate/pull/1629) is ["under consideration"](https://status.modern.ie/webapplicationmanifest) (see also: [this](https://twitter.com/mrlacey/status/572435077558345728) and [this](https://github.com/manifoldjs/ManifoldJS))
- In Windows 10 these files seem to not be used anymore? - Please correct me if I'm wrong! 
  
  I spend some time using Windows 10 (build 10049), and I could no longer find any evidence that the files are still used by Internet Explorer or the browser codename Project Spartan)    
-  Low usage (e.g.: Mozilla [was complaining](https://blog.mozilla.org/futurereleases/2014/03/14/metro/) of low usage of their "metro" app, and I personally seen the same thing with an internal site / web app I've build that is used mainly by Windows 8.1 users - very few of them ever pinned the site in the last 6 months). 
  
  Note: With Windows 10, it seems that Microsoft is moving away from the "metro" start screen to a "metro"-style start menu.
  
  <table>
  <tbody>
      <tr>
          <td>
              
          </td>
      </tr>
      <tr>
          <td align="center">Windows 10 "metro"-style start menu</td>
      </tr>
  </tbody>
  </table>
## 

Thoughts?

### CODE REVIEW

**Comment by patrickkettner** [comment]
paging @jacobrossi

**Comment by voku** [comment]
@alrra I tested some websites with the "Zed Attack Proxy" / "Fiddler" and I saw some 404-errors for "browserconfig.xml" in the logs (with Windows 10 #10061)

spartan_debug

**Comment by alrra** [comment]
> paging @jacobrossi

Update: I pinged @codepo8 in private and he said that he send an email internally and once he has more details he will let us know (probably after Microsoft's Build conference).

--

> and I saw some 404-errors for "browserconfig.xml" in the logs

@voku Can you provide some details on when / why the `browserconfig.xml` file was requested? Thanks!

**Comment by newlpd** [comment]
@alrra WHY YOU NO MERGE THIS??? lame ass!!!

**Comment by jacobrossi** [comment]
These are still supported in Edge. The most recent build enables pinning sites to the start menu, including with live tile images etc.  

We're working on W3C Manifests for hosted apps (currently just through Manifold.js). I'd like to see us deprecate browserconfig.xml and associated meta tags in favor of using a standard JSON manifest. But I don't know of imminent plans to do so quite yet and I believe there's still some work to do on the manifest specification itself.

**Comment by marcoscaceres** [comment]
> But I don't know of imminent plans to do so quite yet and I believe there's still some work to do on the manifest specification itself.

@jacobrossi, let me know of anything you guys need or of any bugs that need prioritization. Spec is getting pretty stable and my implementation in Gecko is almost done. Chrome and Opera are shipping already :)

**Comment by coliff** [comment]
I’m a bit unsure about removing this altogether as it is still used in Windows 8.1 and Windows 10. Also as IE11 and Edge automatically look for browserconfig.xml in the root directory it doesn’t add any bloat/overhead to the default HTML.

I’d suggest keeping this in here for now - at least until Edge adds support for W3C Manifest. (maybe for H5BP v7 :-) )

**Comment by roblarsen** [comment]
closing. as above from @coliff

**Pull request closed without merging**
