### PR TITLE
Minor fix on closure syntax

### PR DESCRIPTION
**Pull request by blckshrk**

### CODE REVIEW

**Comment by drublic** [comment]
Thanks for the suggestion. It think this is a personal preference here.
I personally think `(function () {}())` is easier to understand than `)(function () {})()` since it reminds more of `functionCall()`. Anyway I don't really care about what is used though.
In this case I think we can leave it the way it is.

Thanks again for taking the time for the PR.

**Comment by FagnerMartinsBrack** [comment]
For additional information, check https://youtu.be/eGArABpLy0k?t=1m10s

**Comment by QWp6t** [comment]
wo

@drublic since when are you owner of this repo? congrats. :tada: :balloon:

**Comment by drublic** [comment]
@QWp6t Thank you :) <3

**Comment by blckshrk** [comment]
@drublic You're right, it's only a matter of personal preferences. I found the second style more readable, but that's my opinion.

@FagnerMartinsBrack Thanks for the reference ;-)

**Pull request closed without merging**
