### PR TITLE
Upgrading to babel-preset-env

### PR DESCRIPTION
**Pull request by sumityadav**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This pull request handles upgrading from babel-preset-es2015 which fixes the issue when running `npm install`.
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

### CODE REVIEW

**Comment by jonathantneal** [comment]
It’s unfortunate package.json wasn’t consistently formatted, causing the forced change later in the file (if you used npm to update the file).

**Comment by sumityadav** [comment]
@jonathantneal yes, I used npm install do it and npm removed the whitespace in the repository section of the `package.json`.

The space should not be there anyways. If needed I can go ahead and remove that whitespace change.

**Comment by roblarsen** [comment]
I just tried to resolve the conflict with the online tool. that failed. Not the resolution, that was easy. The change wasn't reflected here, though... weird. @sumityadav if you're around any time over the next 8 hours can you update this PR? Otherwise, I'll do it when I get home.

**Comment by sumityadav** [comment]
@roblarsen I have resolved conflicts and updated the pull request.

**Comment by roblarsen** [comment]
Thanks!

**Pull request merged**
