### PR TITLE
GA commented-out by default (#2379)

### PR DESCRIPTION
**Pull request by TensorTom**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Comment by coliff** [comment]
Thanks for the PR, though I don't think this should be merged. The full IP address is not sent to Google at all when using the `anonymizeIp` feature so the explanation in the docs update in this PR isn't quite right. It has a good explainer here: https://support.google.com/analytics/answer/2763052?hl=en. If we were to not enable Google Analytics in our html template by default, I think it'd be better to remove it altogether and document it in the docs rather than comment it out.

Also, PRs must include updated `/dist/` directory after making a build.

**Comment by roblarsen** [comment]
Thanks for your contribution. Even PRs that don't get merged, like this, help us because it forces us to look at the proposed change and think about where we're at. I agree with @coliff I don't think this is a change we want to pull in.

**Comment by TensorTom** [comment]
Looks like it was closed before I could reply. No matter. I care enough about privacy to reply anyway. I would have disagreed on the basis that the justification for not merging doesn't address the purpose of the merge and is also somewhat inaccurate. I read the docs fully before making the PR.

**Case 1:**

"The full IP address is not sent to Google at all when using the anonymizeIp feature."

This is not true and potentially misleading to new developers. From Google's docs:

"When a customer of Analytics requests IP address anonymization, Analytics anonymizes the address as soon as technically feasible at the earliest possible stage of the collection network."

This means that in fact, your full IP address was sent to Google. That you have already given your customer's/visitors IP addresses to them and are now taking it on faith of ethical good will that Google will always honour a policy. While some people are content to take Google at their word, call me crazy but I am not.

The first thing I did when I saw the GA code was remove it. You may disagree and believe Google's stated intent but I and many others don't. By leaving it on by default, you're saying that you believe most people (If asked) would prefer to have their customers' data sent to Google. I doubt this is the case.

**Case 2:**

Not only is it enabling a privacy concern, it's a needless one. I'd be willing to bet that most the pages that the boilerplate is used for never get connected to a Google Analytics account. This means that users are, by default, likely exposing their users to a privacy risk without even conferring any benefit. This leads directly into...

**Case 3:**

Even worse, this block of code is (by default) adding extra page load time, file-size, and an extra HTTPS connection upon page-load with no benefit to the developer or visitor (Most of the time). I can understand having it in a comment because that might be convenient for a subset of people. To leave it enabled by default though with so many downsides and (Most probably) hardly anyone actually using it makes little sense to me.

**Finally:**

I don't really care if you guys merge such a simple commit that took me all of a few minutes. I was surprised though that a commit with such an obvious technical benefit and zero downsides wasn't merged. Also, I did generate a new dist but I may have forgot to run it after updating the docs.

to each codebase their own I suppose

**Comment by roblarsen** [comment]
Thanks for following up with that. I appreciate the thought you've put into this. To follow up I'll repeat what @coliff said and then add some color

> If we were to not enable Google Analytics in our html template by default, I think it'd be better to remove it altogether and document it in the docs rather than comment it out.

He said the above because, as a design decision that we made many years ago (maybe 8 or so), we don't ship anything extraneous. **We would never ship commented out code.** Proposing that we ship commented out code, no matter how well thought-out the reasoning is behind the change, is a non-starter. We would 💯 remove GA first.

**Pull request closed without merging**
