### PR TITLE
Windows tests

### PR DESCRIPTION
**Pull request by roblarsen**

### CODE REVIEW

**Comment by roblarsen** [comment]
closes #3109 

This is correct behavior. Once one of the two tests in the runner fails, the other one is immediately canceled ("fail fast") 

I still don't know why this test is failing, but we have an automated test for it, so it will never happen again.

**Comment by coliff** [comment]
I'm on Node v18.19.1 on Windows 11 Pro.

`npm run test` is failing:
image

looks like it's related to the `/` path ?

**Comment by roblarsen** [comment]
Failing tests is intentional right now

**Comment by roblarsen** [comment]
> I'm on Node v18.19.1 on Windows 11 Pro.

> looks like it's related to the `/` path ?

Yeah, something changed at some point. It's failing because "\" is not "/" 

v8.0.0 the test worked. I'm going to step through versions of the testing framework to see where it broke.

**Comment by roblarsen** [comment]
And... the tests should be fixed. tl;dr; [node-glob breaking change that I missed being a Codespaces addict](https://github.com/isaacs/node-glob/issues/467)

**Comment by coliff** [comment]
yay! nice one @roblarsen !

image

**Review by coliff — APPROVED** [review]

**Pull request merged**
