### PR TITLE
What about the meta tag, shrink-to-fit=no

### PR DESCRIPTION
**Pull request by raigorx**
https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do
It worth?
I am trying to help please don't blame me

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by raigorx** [comment]
Bootstrap did it

https://getbootstrap.com/docs/4.0/getting-started/introduction/#responsive-meta-tag

**Comment by XhmikosR** [comment]
@roblarsen: this is a good change. Nice explanation: https://bitsofco.de/ios-safari-and-shrink-to-fit/

**Comment by roblarsen** [comment]
thanks for the pointer.  I was busy with 6.0 and just didn't want to add anything new

**Comment by roblarsen** [comment]
I'll pull this in later. i will have to update the docs

**Comment by mathiasbynens** [comment]
This was suggested before: #1815 What has changed since then, @roblarsen?

**Pull request merged**
