### PR TITLE
add keywords in package.json

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by kevva** [comment]
This isn't published to npm so it doesn't makes sense.

**Comment by PeterDaveHello** [comment]
It won't bite :smile:

**Comment by kevva** [comment]
No, but it's simply not useful.

**Comment by PeterDaveHello** [comment]
In fact, I saw a request to add this framework on public cdn, it'll be nice to have keywords in package.json!

**Comment by drublic** [comment]
HTML5 Boilerplate is more of a template than a framework. What would you
add to a CDN or npm registry?
I don't think we need this.

**Comment by PeterDaveHello** [comment]
Ok, thanks!

**Pull request closed without merging**
