### PR TITLE
Update CHANGELOG.md for v6.1

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by Amorn-Kingthong** [comment]
Leave a comment ok

**Comment by roblarsen** [comment]
Aw heck, let's make a release

**Comment by coliff** [comment]
Cool - shall I update 'package.json' with new version number? also we should add todays date on the changelog - right now it says unreleased.

**Comment by roblarsen** [comment]
Sure, start a new PR for the release so we can get one clean commit for everything

**Pull request merged**
