### PR TITLE
Fix typo in .htaccess

### PR DESCRIPTION
**Pull request by hnarayanan**
This pull request fixes a small typo identified in #1707.

### CODE REVIEW

**Comment by QWp6t** [comment]
very important, pls merge right away

**Comment by Alhadis** [comment]
30 MINUTES HAS PASSED AND THERE'S NO FIX, IS THIS PROJECT DEAD ***OR WHAT?!!*** :'(

**Comment by drublic** [comment]
@hnarayanan Thank you for the fix. Can you please open this PR against [h5bp/server-configs-apache](https://github.com/h5bp/server-configs-apache)? We import `.htaccess` from there.

**Comment by hnarayanan** [comment]
Will do so shortly.

**Comment by drublic** [comment]
Perfect. Thank you @hnarayanan.

**Pull request closed without merging**
