### PR TITLE
Add codeql-analysis.yml

### PR DESCRIPTION
**Pull request by coliff**
Fixes: #2785

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by roblarsen** [comment]
This is good. I'll uninstall LGTM. To the theme of best practices that I'm working on in the docs, CodeQL is where it's at.

**Comment by coliff** [comment]
> This is good. I'll uninstall LGTM. To the theme of best practices that I'm working on in the docs, CodeQL is where it's at.

I'd actually recommend keeping LGTM too. They are very similar but I've noticed that LGTM can catch coding errors that the security-focused CodeQL does not.

**Comment by roblarsen** [comment]
> > This is good. I'll uninstall LGTM. To the theme of best practices that I'm working on in the docs, CodeQL is where it's at.
> 
> I'd actually recommend keeping LGTM too. They are similar but I've noticed that LGTM can catch coding errors that the security-focused CodeQL does not.

Interesting. We'll keep both. We're not paying for the processing time!

**Review by roblarsen — APPROVED** [review]
🚢

**Pull request merged**
