### PR TITLE
Add Google Tag Manager instead of Google Analytics

### PR DESCRIPTION
**Pull request by JohnnyWalkerDesign**
Google Tag Manager allows for better control over inserted tags, like Google Analytics, as well the ability to quickly add/update/remove tags without needing to modify your code. Preferable?

From Google's documentation:

*“Google Tag Manager is an asynchronous tag, meaning that when it executes, it does not block other elements from rendering on the page. It also causes the other tags that are deployed via Google Tag Manager to be deployed asynchronously, meaning that a slow loading tag won’t block other tracking tags.”*

https://developers.google.com/tag-manager/devguide

### CODE REVIEW

**Comment by QWp6t** [comment]
:-1:

**Comment by JohnnyWalkerDesign** [comment]
Thanks for the well-reasoned and considered addition to this discussion. I was a skeptic when I started reading, but you convinced me by the end.

**Comment by webhat** [comment]
Implementing Google Tag Manager is none trivial, and in my experience there is no great benefit if you are not running a site that requires all the enhancements such as an ecommerce site.

**Comment by lkraav** [comment]
Indeed. Tag management is for people who know they need it, not so much suitable for a hardcoded default thing. Raising awareness, always a good thing, could still be accomplished by a documentation patch.

**Comment by JohnnyWalkerDesign** [comment]
I wouldn't say that GTM is "non trivial". It's slightly more complicated than GA, but only slightly, and is a solution that's future proofed (as far as we can tell) once done. Still, if the general consensus is that it's not an improvement, fair enough.

**Comment by roblarsen** [comment]
FWIW, there have been a couple of previous discussions of removing Google Analytics altogether or replacing it with other opens #1275 #1547 #1548

**Comment by JohnnyWalkerDesign** [comment]
Well this isn't about removing GA, and wouldn't appease those who aren't fans of Google :)

**Comment by roblarsen** [comment]
I'm just adding links to relevant issues from the past.

**Comment by paulirish** [comment]
Thanks for the PR. 

I've actually never used GTM, personally. Swapping these snippets is pretty easy, so I think it's alright to leave our optimized GA snippet in place for the default user.

**Pull request closed without merging**
