### PR TITLE
::first-letter and ::first-line pseudo-elements are now printed in black

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by drublic** [comment]
Thanks for the contribution. Makes sense to support these pseudo elements too.

Currently we still support IE8 and thus have to use `:first-letter` and `:first-line` I think.
Apart from that, could you please add a note in our `CHANGELOG.md` file?

**Comment by SidRoberts** [comment]
@drublic Done. :smile:

**Comment by drublic** [comment]
Thank you, @SidRoberts! Any other opinions?

**Comment by SidRoberts** [comment]
Nope, I'm happy. :smile:

**Comment by drublic** [comment]
Thanks again for your work. Now finally landed in master.

**Pull request closed without merging**
