### PR TITLE
Release 9.0.0

### PR DESCRIPTION
**Pull request by roblarsen**
Kicking off the release. I think the main repo is ready to go, mostly, although things will obviously shake out over the next few days.  I have to look clearly at the site.

### CODE REVIEW

**Comment by coliff** [comment]
On vacation for a few weeks and don’t have too much time to review in detail, but I think we should update all dev deps before release. Version number needs updating in package-lock.json too. A lot of the docs need reviewing and updating, but I think that could be done separately.

**Comment by roblarsen** [comment]
I guess I can just release this?

**Comment by coliff** [comment]
Let's have a week to properly go through all the docs and get everything in shape before making a release. I'll try and do a little bit every day.

**Comment by roblarsen** [comment]
I'm starting on the changelog right now.

**Comment by roblarsen** [comment]
@coliff Anything else here?

**Comment by coliff** [comment]
@roblarsen - Can I have 1 final, last day to review the docs - so set the deadline for tomorrow?

**Comment by coliff** [comment]
Fixed some docs stuff, pushed a commit and squashed it with yesterdays one. Ok from my side now. 👍

**Pull request merged**
