### PR TITLE
Resolves closed Greenkeeper PRs

### PR DESCRIPTION
**Pull request by caraya**
Resolves #1870, #1869, #1868 and #1864

jQuery is upgrading from version 1 to version 3. It may be a good idea to point to the upgrade guide somewhere to people know where to look in case something breaks.

### CODE REVIEW

**Comment by coliff** [comment]
Changing H5BP to use/recommend jQuery 3 means that IE8 is no longer supported though. If that is the case it should very clearly state that - or perhaps there should be a major new version of H5BP (v6) which drops all support for IE8. (Support for IE7 was dropped with v5 of H5BP.)

**Comment by caraya** [comment]
I'm ok reverting the commit and changing it back to a version 2. I'll wait to see what committers say on the matter

**Comment by coliff** [comment]
Hi again. Yep I saw  #1524. So for now H5BP should use jQuery 1.12.4 which is the latest IE8 compatible version. jQuery 2.x doesn't support IE8 at all.

**Comment by caraya** [comment]
moved back to jQuery 1.12.4 while waiting for further discussion on dropping IE8 support

**Comment by roblarsen** [comment]
@caraya Yeah, the jQuery dev dependency is what's pushed into the index.html, so upgrading to 3.* shouldn't happen in this commit.  #1524 will handle that and everything else we need to do to finally unshackle ourselves from the deep past. As for the other upgrades in this PR does anything break?  If not, squash the two commits and create a commit message that describes the changes (what you're upgrading.). Since it will likely run long, put the issues that it closes in the body of the commit message. Then LGTM +1

**Comment by caraya** [comment]
The last commit to this PR upgraded jQuery to 1.12.4. It's good to go

**Comment by roblarsen** [comment]
Yeah, saw that. Thanks! You should still [http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html](squash) the commits and update the commit message to something that describes the changes you're making.

**Comment by caraya** [comment]
No, tested the commits by running Gulp tasks that used the plugins and couldn't break it. 

Something weird happened when I rebased and it caused two commits.  Sorry, still learning how to rebase

**Comment by roblarsen** [comment]
@caraya It's a little weird if you haven't done it. If you can't figure it out, feel free to create a fresh PR with just the required changes and close this one.

**Pull request closed without merging**
