### PR TITLE
Add `og:image:alt` for accessibility.

### PR DESCRIPTION
**Pull request by aartaka**
## Add image alt text in index.html

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

This ensures that the image added via OpenGraph `<meta>` tag has a proper alt text for use with screen readers or image-less user agents. Leaving the alt text empty is a sane fallback for when the image is purely decorative too.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Documentation and tests are irrelevant for such a change, right?

### CODE REVIEW

**Comment by roblarsen** [comment]
I'll have to take a look at this! Thanks for your submission.

**Comment by coliff** [comment]
The HTML file needs to be updated in the `src/` folder too.
Other than that, 👍 from me.
REF: https://ogp.me/#structured

**Comment by aartaka** [comment]
Added the code to `src/index`, `docs/html` and `docs/extend`, seems that I've covered everything. 

I barely resisted the temptation to add Twitter cards image alt too, but that's for a different PR!

**Review by roblarsen — APPROVED** [review]
Thanks!

**Pull request merged**
