### PR TITLE
Add defer attribute to script tag in footer (index.html)

### PR DESCRIPTION
**Pull request by Utwo**
Add defer attribute to <script />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by coliff** [comment]
All the scripts are in the footer of the page - what's the need to add defer to them all?

**Comment by Utwo** [comment]
Yes, because here are 2 or 3 scripts that need to load. We don't want to wait for the first one to download completely and only after that to load the second one. 
At least this is how I understand it.
More info here:
http://contentloaded.com/dom-ready/?head=style:500&body=html:1000;watch:1000;jquery:1000,defer;script:500,defer

**Comment by mathiasbynens** [comment]
https://github.com/h5bp/lazyweb-requests/issues/42

**Comment by tomasz1986** [comment]
What if the later scripts depend on the previous ones? If there are things that depend on Modernizr and jQuery, then they will break if the two libraries have not been loaded before.

**Comment by Utwo** [comment]
Scripts are loaded async and run in order of appearance.

**Comment by Utwo** [comment]
Yap, I agree!

**Pull request closed without merging**
