### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ishaan2053**
## Types of changes

- [x] New feature: Improvement/update of Readme.md (**Non Code**)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Changes Included:
- Shortened links
- Corrected typos
- Added necessary punctuation, rephrased some text
- Improved uniformity of text

### CODE REVIEW

**Comment by roblarsen** [comment]
This looks good! Thank you

**Comment by Ishaan2053** [comment]
Thank you🫂

**Review by roblarsen — APPROVED** [review]
I'm going to merge these in, as is, and then pick up the few small edits I would be requesting myself. Sometimes... the back and forth on editorial stuff is painful, so I'll just make the small changes myself in the "update dist" branch that will follow the merge of this PR. Thanks @Ishaan2053 nice attention to detail and thank you for the new set of eyes on this doc.

**Comment by Ishaan2053** [comment]
Always happy to contribute 🙂🫂

**Pull request merged**
