### PR TITLE
Add SRI Hash for jQuery

### PR DESCRIPTION
**Pull request by mik-laj**
Hi my friend,

I want add a new freature - generating SRI Hash for external depedencies from CDN. 
You could read more about it on: 
https://www.srihash.org/ 
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

It should be emphasized that the official website of jQuery supports this technology:
https://github.com/jquery/codeorigin.jquery.com/issues/20

You should look at: 
http://caniuse.com/#feat=subresource-integrity

Thanks in advance

### CODE REVIEW

**Comment by roblarsen** [comment]
@mik-laj The tests are failing.

**Comment by mik-laj** [comment]
@roblarsen I do not have access to the logs. Could you show them to me?

**Comment by roblarsen** [comment]
1. You can run the tests locally (`npm install, npm test`)
2. If you're on Github you're staring at the logs. Click on the "All checks have failed"

image

**Comment by mik-laj** [comment]
1. Thanks bro. I fixed code:-) 
2. I have found logs. I did not use often matrix tests.  I did not notice that I have something I have to click.

**Comment by roblarsen** [comment]
@mik-laj that's what I'm here for.

**Comment by mik-laj** [comment]
Test passed

**Comment by roblarsen** [comment]
THANKS!

**Pull request merged**
