### PR TITLE
Fixes #1742

### LINKED ISSUE #1742: Print style for code block
On some sites, code block are not wrapped when printed. This is bad as I'm one of the people who love printing some articles to read later or archived it.

Currently I use stylish to inject style below to all site.

```css
@media print {
  pre {
    white-space: pre-wrap !important;
  }
}
```

I think its good to add that style or maybe someone have another idea ?

### PR DESCRIPTION
**Pull request by claughlin-r7**
Adding pre-wrap to pre and blockquote for print media query as per @akhyarrh issue.

### CODE REVIEW

**Comment by akhyarrh** [comment]
Clean your commit or create another PR
:+1:

**Comment by claughlin-r7** [comment]
@akhyarrh is the current code okay or do I need to change it

**Comment by akhyarrh** [comment]
LGTM :+1:

**Comment by StephenBrown2** [comment]
My bad, the github diff only showed the blockquote part.

blockquotes do need wrapping too, I'm sure, but #1742 only mentioned pre

**Comment by akhyarrh** [comment]
`blockquote` wrapped automaticaly. You can check using this:

```html
<blockquote><p>Following these guidelines helps to communicate that you respect the time of the developers managing and developing this open source project. In return, they should reciprocate that respect in addressing your issue or assessing patches and features. A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.</p></blockquote>
```

**Comment by roblarsen** [comment]
@claughlin-r7 Can you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) those two commits and change the commit message to something that describes the change? Something like `Adds pre-wrap to BLOCKQUOTE and PRE fixes #1742`

**Comment by claughlin-r7** [comment]
@roblarsen updated PR

**Comment by akhyarrh** [comment]
Style only applied to `pre`. Maybe you need to change your commit message
again ?

**Comment by roblarsen** [comment]
@akhyarrh Good eye. Yeah, sorry about that @claughlin-r7 but I should have been more careful with my example. Remove "BLOCKQUOTE" and this is good to go. I'll be working through issues later on today.

**Comment by claughlin-r7** [comment]
@roblarsen commit message updated.

**Comment by roblarsen** [comment]
Thanks!

**Pull request merged**
