### PR TITLE
Adds web app manifest file

### PR DESCRIPTION
**Pull request by roblarsen**
closes #1629

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

This is a clean update of the original PR. The changes were easy enough and I was eyeing that other PR warily. 

I'll add documentation this week as part of a documentation pass (unless someone else wants to add some documentation- I will merge the heck out of those PRs)

### CODE REVIEW

**Comment by ArmorDarks** [comment]
Why file had been named that way? Shouldn't it be `manifest.json`?

**Comment by coliff** [comment]
oops. realised we don't have any documentation about the webapp manifest. I'll get something together and make a PR.

**Comment by roblarsen** [comment]
It's in the HTML docs, but is very basic.

**Comment by coliff** [comment]
ah yes, sorry. That looks fine actually...

**Pull request merged**
