### PR TITLE
Updates for gulp 5

### PR DESCRIPTION
**Pull request by roblarsen**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Comment by coliff** [comment]
Test failure:
image

**Comment by roblarsen** [comment]
@coliff tests are passing here and in my codespace. Can you double check?

**Comment by coliff** [comment]
Tested on Windows 11 before - get a different error on macOS
Untitled

[.DS_Store](https://en.m.wikipedia.org/wiki/.DS_Store) is in our .gitignore but should ideally set it to be excluded from dist dir too.

**Comment by Koribraide** [comment]
> @coliff tests are passing here and in my codespace. Can you double check?

whats the issue ?

**Comment by coliff** [comment]
> > @coliff tests are passing here and in my codespace. Can you double check?
> 
> whats the issue ?

npm run build passes, but npm run test does not on my Windows 11 PC. I tried a few things including deleting node_modules and reinstalling. Do you want to give it a try?

image

**Comment by Koribraide** [comment]
hmmm, what is the result supposed to look like?

**Comment by coliff** [comment]
> hmmm, what is the result supposed to look like?

Pass with no errors

**Comment by roblarsen** [comment]
BREAKING NEWS

I just checked out the v9.0.0 tag and it's broken there. 

So... I don't know when this test last passed on Windows. I am actually on Windows as I type this but I've become a Codespaces devotee so I did the entire 9.0.0 release on GitHub and the PR tests are all running in similar environments. I'm going to backwards through tags to find out when it last worked at start from there. It definitely used to work because before Codepsaces everything I did went through Windows. 

The issue is that "css\style.css" is not "css/style.css" 

```
 'webpack.common.js',
  'webpack.config.dev.js',
  'webpack.config.prod.js',

  'css/', // for directories, a `/` character
  // should be included at the end
  'css/style.css',
```


```
 16) Test if all the expected files, and only them, are present in the build directories
       dist
         "css\style.css" should NOT be present:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:        

  assert(false)

      + expected - actual

      -false
      +true
````
 
@coliff I'd like to merge this PR and then I'll create a separate issue for the failing tests since they pre-date the Gulp upgrade.  Once I fix that we'll put out a patch release.

**Review by coliff — APPROVED** [review]

**Comment by Koribraide** [comment]
@coliff fixed?

**Comment by roblarsen** [comment]
> @coliff fixed?

[See above](https://github.com/h5bp/html5-boilerplate/pull/3105#issuecomment-2043580746)

**Pull request merged**
