### PR TITLE
feat(build): parcel (#2227)

### LINKED ISSUE #2227: Include bundler
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below)

Not sure if necessary, so it's more like a question/discussion, but in my point of view if I would want to make some static HTML page using html5-boilerplate I would definitely use bundler for my JS and CSS (probably would go for SCSS).
So I would use webpack or parcel to be able to use modern javascript and etc. So it would be comfortable for me if html5-boilerplate includes default webpack configuration, so I'll be able right away just to `npm install` and `npm run build`.

What do you think? Or maybe I miss the point of the html5-boilerplate and its not relevant?

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

closes #2227

### CODE REVIEW

**Comment by vltansky** [comment]
Hi, I've synced my branch with latest changes.

**Comment by roblarsen** [comment]
Awesome. This looks good. I'm going to make some changes to this myself and then we can look at the other feature

**Comment by vltansky** [comment]
Ok, let me know if you want any help, I'd be happy :)

**Comment by roblarsen** [comment]
I will. Thanks for proposing this, this is a great feature and parcel is so unobtrusive I think it fits perfectly with the way we'd like to do things.

**Pull request merged**
