### PR TITLE
add keywords meta-tag

### PR DESCRIPTION
**Pull request by marcobiedermann**
add keywords meta-tag
`<meta name="keywords" content="">`

### CODE REVIEW

**Comment by patrickkettner** [comment]
https://www.youtube.com/watch?v=jK7IPbnmvVU

"Google does not use the keywords meta tag in web ranking"

**Comment by marcobiedermann** [comment]
@patrickkettner I know, how about other search engines?

**Comment by patrickkettner** [comment]
No major search engine looks at the meta keywords. its been rife with spam for far too long

**Comment by roblarsen** [comment]
It's been that way for at least 7-8 years IRT Google.

**Comment by alrra** [comment]
> No major search engine looks at the meta keywords. its been rife with spam for far too long

@marcobiedermann :point_up:

**Comment by patrickkettner** [comment]
http://blogs.bing.com/webmaster/2014/10/03/blame-the-meta-keyword-tag/ - bing doesn't either.

**Pull request closed without merging**
