### PR TITLE
HTTPS links

### PR DESCRIPTION
**Pull request by coliff**
Safer and faster

### CODE REVIEW

**Comment by tomasz1986** [comment]
Safer, yes, but isn't HTTPS always slower than HTTP, especially on mediocre connections (e.g. mobile like 3G)? I am no expert in this field but from my experience and understanding there is quite a noticeable negative impact on how quickly websites load (particularly during the initial load, with no pre-cached files).

https://stackoverflow.com/questions/149274/http-vs-https-performance

I am not opposed to the change, only asking.

**Comment by roblarsen** [comment]
If a site has implemented https, they're **hopefully** redirecting all http traffic to the secure version of that same resource. In that case, if we are pointing to an insecure resource and the server has to redirect the user that's always going to be _slower_ for the end user since they have to go through the redirect step. Skipping the redirection step by pointing directly at the secure resource is faster in that case, not matter what the difference is between http and https in terms of performance.

**Comment by coliff** [comment]
Yep - HTTPS is important and advantageous. I like this site for explaining why: https://doesmysiteneedhttps.com/

In fact, maybe we should have a little section about HTTPS in the Extend section...

**Comment by tomasz1986** [comment]
> If a site has implemented https, they're hopefully redirecting all http traffic to the secure version of that same resource.

Right, I was thinking about a situation where the same content is available through both HTTP and HTTPS. In this case everything is to go through HTTPS anyway. Thank you for a detailed explanation.

**Comment by Amorn-Kingthong** [comment]
never mind

**Pull request merged**
