### PR TITLE
deprecate protocol relative URLs

### PR DESCRIPTION
**Pull request by patrickkettner**
https://twitter.com/paul_irish/status/588502455530311680

### CODE REVIEW

**Comment by drublic** [comment]
Sounds good to me.

**Comment by mathiasbynens** [comment]
This is a no-brainer, especially given eee759bfe175e850bbc8e4ad0682ec4fe4bd05d6. Thanks for bringing it up!

**Comment by patrickkettner** [comment]
:+1:

**Comment by arthurvr** [comment]
:+1: Thanks @patrickkettner!

**Comment by patrickkettner** [comment]
not to beat a dead horse, but.... https://twitter.com/souders/status/588750637912883200

"Google redirects http to https for their scripts, so u get better #WebPerf by updating Google snippets to always be https" - @stevesouders

**Pull request closed without merging**
