### PR TITLE
Creating an svg icon

### LINKED ISSUE #2554: Include a SVG favicon
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

I think we should add a SVG favicon to the root of the project. SVG favicons are support by all major browsers. As they are scalable vectors they typically have a smaller file size than a larger 24-bit PNG and can support dark mode via a media query.

This is a great post: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
and I agree with the conclusion that all you need is:

```html
<link rel="icon" href="/favicon.ico"><!-- 32×32 -->
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png"><!-- 180×180 -->
<link rel="manifest" href="/manifest.webmanifest">
```

### PR DESCRIPTION
**Pull request by roblarsen**
The svg icon needs to be cleaned up

closes #2554

### CODE REVIEW

**Comment by coliff** [comment]
yep, I think we should make the size of the SVG a square, remove the background, then minify with https://jakearchibald.github.io/svgomg/

**Comment by sadique43** [comment]
Creating vector icon would be better than svg in this regard.

**Comment by roblarsen** [comment]
Fixing tests up in here

**Comment by coliff** [comment]
I'm working on this now. I've minified the SVG and it's down to 272 bytes gzipped. I'm adding the necessary meta tags to the index.html too.

```html
  <link rel="icon" href="favicon.ico" sizes="any">
  <link rel="icon" href="icon.svg" type="image/svg+xml">
```

One thing left to do though - the main star in the icon isn't centred horizontally perfectly so it looks very f slightly off. I'll edit that.

image

**Comment by coliff** [comment]
@roblarsen - shall we go with the transparent one then? If so, I'll push a commit with the it added.
Test URL with it here: https://tests.christianoliff.com/h5bp-favicon/

**Comment by roblarsen** [comment]
> @roblarsen - shall we go with the transparent one then? If so, I'll push a commit with it added. Test URL with it here: https://tests.christianoliff.com/h5bp-favicon/

Let's go with the transparent one

**Pull request closed without merging**
